
namespace GesMgmt.Domain.Entities
{
    public class av_DocxCobrarParam //: BaseEntity
    {
        public int nId_DocxCobrarParam { get; set; }

        public int? nId_Cartera { get; set; }
        public int nId_DocxCobrar { get; set; }

        public virtual av_Cartera av_Cartera { get; set; }
        public virtual av_DocxCobrar av_DocxCobrar { get; set; }

        public int? bEstado { get; set; }
        public string? cDocParam01 { get; set; }
        public string? cDocParam02 { get; set; }
        public string? cDocParam03 { get; set; }
        public string? cDocParam04 { get; set; }
        public string? cDocParam05 { get; set; }
        public string? cDocParam06 { get; set; }
        public string? cDocParam07 { get; set; }
        public string? cDocParam08 { get; set; }
        public string? cDocParam09 { get; set; }
        public string? cDocParam10 { get; set; }
        public string? cDocParam11 { get; set; }
        public string? cDocParam12 { get; set; }
        public string? cDocParam13 { get; set; }
        public string? cDocParam14 { get; set; }
        public string? cDocParam15 { get; set; }
        public string? cDocParam16 { get; set; }
        public string? cDocParam17 { get; set; }
        public string? cDocParam18 { get; set; }
        public string? cDocParam19 { get; set; }
        public string? cDocParam20 { get; set; }
        public string? cDocParam21 { get; set; }
        public string? cDocParam22 { get; set; }
        public string? cDocParam23 { get; set; }
        public string? cDocParam24 { get; set; }
        public string? cDocParam25 { get; set; }
        public string? cDocParamZona { get; set; }
        public int? nId_cliente { get; set; }
        //public av_Cliente av_Cliente { get; set; }
        public string? cDocParam26 { get; set; }
        public string? cDocParam27 { get; set; }
        public string? cDocParam28 { get; set; }
        public string? cDocParam29 { get; set; }
        public string? cDocParam30 { get; set; }
        public string? cDocParam31 { get; set; }
        public string? cDocParam32 { get; set; }
        public string? cDocParam33 { get; set; }
        public string? cDocParam34 { get; set; }
        public string? cDocParam35 { get; set; }
        public string? cDocParam36 { get; set; }
        public string? cDocParam37 { get; set; }
        public string? cDocParam38 { get; set; }
        public string? cDocParam39 { get; set; }
        public string? cDocParam40 { get; set; }
        public string? cDocParam41 { get; set; }
        public string? cDocParam42 { get; set; }
        public string? cDocParam43 { get; set; }
        public string? cDocParam44 { get; set; }
        public string? cDocParam45 { get; set; }
        public string? cDocParam46 { get; set; }
        public string? cDocParam47 { get; set; }
        public string? cDocParam48 { get; set; }
        public string? cDocParam49 { get; set; }
        public string? cDocParam50 { get; set; }
        public string? cDocParam51 { get; set; }
        public string? cDocParam52 { get; set; }
        public string? cDocParam53 { get; set; }
        public string? cDocParam54 { get; set; }
        public string? cDocParam55 { get; set; }
        public string? cDocParam56 { get; set; }
        public string? cDocParam57 { get; set; }
        public string? cDocParam58 { get; set; }
        public string? cDocParam59 { get; set; }
        public string? cDocParam60 { get; set; }
        public string? cDocParam61 { get; set; }
        public string? cDocParam62 { get; set; }
        public string? cDocParam63 { get; set; }
        public string? cDocParam64 { get; set; }
        public string? cDocParam65 { get; set; }
        public string? cDocParam66 { get; set; }
        public string? cDocParam67 { get; set; }
        public string? cDocParam68 { get; set; }
        public string? cDocParam69 { get; set; }
        public string? cDocParam70 { get; set; }
        public string? cDocParam71 { get; set; }
        public string? cDocParam72 { get; set; }
        public string? cDocParam73 { get; set; }
        public string? cDocParam74 { get; set; }
        public string? cDocParam75 { get; set; }
        public string? cDocParam76 { get; set; }
        public string? cDocParam77 { get; set; }
        public string? cDocParam78 { get; set; }
        public string? cDocParam79 { get; set; }
        public string? cDocParam80 { get; set; }
        public string? cDocParam81 { get; set; }
        public string? cDocParam82 { get; set; }
        public string? cDocParam83 { get; set; }
        public string? cDocParam84 { get; set; }
        public string? cDocParam85 { get; set; }
        public string? cDocParam86 { get; set; }
        public string? cDocParam87 { get; set; }
        public string? cDocParam88 { get; set; }
        public string? cDocParam89 { get; set; }
        public string? cDocParam90 { get; set; }
        public string? cDocParam91 { get; set; }
        public string? cDocParam92 { get; set; }
        public string? cDocParam93 { get; set; }
        public string? cDocParam94 { get; set; }
        public string? cDocParam95 { get; set; }
        public string? cDocParam96 { get; set; }
        public string? cDocParam97 { get; set; }
        public string? cDocParam98 { get; set; }
        public string? cDocParam99 { get; set; }
        public string? cDocParam100 { get; set; }
        public int? nId_UsuarioUpd { get; set; }
        public string? cDocParamCliCar { get; set; }
        public string? cDocParamZonaCli { get; set; }
        public string? cDocParam101 { get; set; }
        public string? cDocParam102 { get; set; }
        public string? cDocParam103 { get; set; }
        public string? cDocParam104 { get; set; }
        public string? cDocParam105 { get; set; }
        public string? cDocParam106 { get; set; }
        public string? cDocParam107 { get; set; }
        public string? cDocParam108 { get; set; }
        public string? cDocParam109 { get; set; }
        public string? cDocParam110 { get; set; }
        public string? cDocParam111 { get; set; }
        public string? cDocParam112 { get; set; }
        public string? cDocParam113 { get; set; }
        public string? cDocParam114 { get; set; }
        public string? cDocParam115 { get; set; }
        public string? cDocParam116 { get; set; }
        public string? cDocParam117 { get; set; }
        public string? cDocParam118 { get; set; }
        public string? cDocParam119 { get; set; }
        public string? cDocParam120 { get; set; }
        public string? cDocParam121 { get; set; }
        public string? cDocParam122 { get; set; }
        public string? cDocParam123 { get; set; }
        public string? cDocParam124 { get; set; }
        public string? cDocParam125 { get; set; }
        public string? cDocParam126 { get; set; }
        public string? cDocParam127 { get; set; }
        public string? cDocParam128 { get; set; }
        public string? cDocParam129 { get; set; }
        public string? cDocParam130 { get; set; }
        public string? cDocParam131 { get; set; }
        public string? cDocParam132 { get; set; }
        public string? cDocParam133 { get; set; }
        public string? cDocParam134 { get; set; }
        public string? cDocParam135 { get; set; }
        public string? cDocParam136 { get; set; }
        public string? cDocParam137 { get; set; }
        public string? cDocParam138 { get; set; }
        public string? cDocParam139 { get; set; }
        public string? cDocParam140 { get; set; }
        public string? cDocParam141 { get; set; }
        public string? cDocParam142 { get; set; }
        public string? cDocParam143 { get; set; }
        public string? cDocParam144 { get; set; }
        public string? cDocParam145 { get; set; }
        public string? cDocParam146 { get; set; }
        public string? cDocParam147 { get; set; }
        public string? cDocParam148 { get; set; }
        public string? cDocParam149 { get; set; }
        public string? cDocParam150 { get; set; }
        public string? cDocParam151 { get; set; }
        public string? cDocParam152 { get; set; }
        public string? cDocParam153 { get; set; }
        public string? cDocParam154 { get; set; }
        public string? cDocParam155 { get; set; }
        public string? cDocParam156 { get; set; }
        public string? cDocParam157 { get; set; }
        public string? cDocParam158 { get; set; }
        public string? cDocParam159 { get; set; }
        public string? cDocParam160 { get; set; }
        public string? cDocParam161 { get; set; }
        public string? cDocParam162 { get; set; }
        public string? cDocParam163 { get; set; }
        public string? cDocParam164 { get; set; }
        public string? cDocParam165 { get; set; }
        public string? cDocParam166 { get; set; }
        public string? cDocParam167 { get; set; }
        public string? cDocParam168 { get; set; }
        public string? cDocParam169 { get; set; }
        public string? cDocParam170 { get; set; }
        public string? cDocParam171 { get; set; }
        public string? cDocParam172 { get; set; }
        public string? cDocParam173 { get; set; }
        public string? cDocParam174 { get; set; }
        public string? cDocParam175 { get; set; }
        public string? cDocParam176 { get; set; }
        public string? cDocParam177 { get; set; }
        public string? cDocParam178 { get; set; }
        public string? cDocParam179 { get; set; }
        public string? cDocParam180 { get; set; }
        public string? cDocParam181 { get; set; }
        public string? cDocParam182 { get; set; }
        public string? cDocParam183 { get; set; }
        public string? cDocParam184 { get; set; }
        public string? cDocParam185 { get; set; }
        public string? cDocParam186 { get; set; }
        public string? cDocParam187 { get; set; }
        public string? cDocParam188 { get; set; }
        public string? cDocParam189 { get; set; }
        public string? cDocParam190 { get; set; }
        public string? cDocParam191 { get; set; }
        public string? cDocParam192 { get; set; }
        public string? cDocParam193 { get; set; }
        public string? cDocParam194 { get; set; }
        public string? cDocParam195 { get; set; }
        public string? cDocParam196 { get; set; }
        public string? cDocParam197 { get; set; }
        public string? cDocParam198 { get; set; }
        public string? cDocParam199 { get; set; }
        public string? cDocParam200 { get; set; }
        public string? cDocParam201 { get; set; }
        public string? cDocParam202 { get; set; }
        public string? cDocParam203 { get; set; }
        public string? cDocParam204 { get; set; }
        public string? cDocParam205 { get; set; }
        public string? cDocParam206 { get; set; }
        public string? cDocParam207 { get; set; }
        public string? cDocParam208 { get; set; }
        public string? cDocParam209 { get; set; }
        public string? cDocParam210 { get; set; }
        public string? cDocParam211 { get; set; }
        public string? cDocParam212 { get; set; }
        public string? cDocParam213 { get; set; }
        public string? cDocParam214 { get; set; }
        public string? cDocParam215 { get; set; }
        public string? cDocParam216 { get; set; }
        public string? cDocParam217 { get; set; }
        public string? cDocParam218 { get; set; }
        public string? cDocParam219 { get; set; }
        public string? cDocParam220 { get; set; }
        public string? cDocParam221 { get; set; }
        public string? cDocParam222 { get; set; }
        public string? cDocParam223 { get; set; }
        public string? cDocParam224 { get; set; }
        public string? cDocParam225 { get; set; }
        public string? cDocParam226 { get; set; }
        public string? cDocParam227 { get; set; }
        public string? cDocParam228 { get; set; }
        public string? cDocParam229 { get; set; }
        public string? cDocParam230 { get; set; }
        public string? cDocParam231 { get; set; }
        public string? cDocParam232 { get; set; }
        public string? cDocParam233 { get; set; }
        public string? cDocParam234 { get; set; }
        public string? cDocParam235 { get; set; }
        public string? cDocParam236 { get; set; }
        public string? cDocParam237 { get; set; }
        public string? cDocParam238 { get; set; }
        public string? cDocParam239 { get; set; }
        public string? cDocParam240 { get; set; }
        public string? cDocParam241 { get; set; }
        public string? cDocParam242 { get; set; }
        public string? cDocParam243 { get; set; }
        public string? cDocParam244 { get; set; }
        public string? cDocParam245 { get; set; }
        public string? cDocParam246 { get; set; }
        public string? cDocParam247 { get; set; }
        public string? cDocParam248 { get; set; }
        public string? cDocParam249 { get; set; }
        public string? cDocParam250 { get; set; }
        public string? cDocParam_SBS_CantidadEmpresas { get; set; }
        public string? cDocParam_SBS_Calificacion_AVAL { get; set; }
        public string? cDocParam_SBS_Calificacion { get; set; }
        public string? cDocParam_SBS_Calificacion_Normal { get; set; }
        public string? cDocParam_SBS_Calificacion_CPP { get; set; }
        public string? cDocParam_SBS_Calificacion_Deficiente { get; set; }
        public string? cDocParam_SBS_Calificacion_Dudoso { get; set; }
        public string? cDocParam_SBS_Calificacion_Perdida { get; set; }
        public string? cDocParam_SBS_Ponderado { get; set; }
        public string? cDocParam_Essalud_SUELDO { get; set; }
        public string? cDocParam_Essalud_Situacion { get; set; }
        public string? cDocParam_Essalud_NombreEmpresa { get; set; }
        public string? cDocParam_Essalud_Fecha { get; set; }
        public string? cDocParam_Essalud_cntMensual { get; set; }
        public string? cDocParam_Essalud_sueldoMensual { get; set; }
        public string? cDocParam_cntveces { get; set; }
        public string? cDocParam_cntveceshis { get; set; }
        public string? cDocParam_rango_veces { get; set; }
        public string? cDocParam_cntveces_consecutiva { get; set; }
        public string? cDocParam_rango_veces_consecutiva { get; set; }
        public string? cDocParam_cntveces_pago_his { get; set; }
        public string? cDocParam_cntveces_pago_his_contacto { get; set; }
        public string? cDocParam_cntveces_pago_his_No_contacto { get; set; }
        public string? cDocParam_cntveces_pago_6camp { get; set; }
        public string? cDocParam_cntveces_pago_6camp_contacto { get; set; }
        public string? cDocParam_cntveces_pago_6camp_No_contacto { get; set; }
        public string? cDocParam_maxFecContacto { get; set; }
        public string? cDocParam_cntdias_maxFecContacto { get; set; }
        public string? cDocParam_rangodias_maxFecContacto { get; set; }
    }
}