namespace GesMgmt.Domain.Entities
{
    public class av_DocxCobrarParamOpe
    {
        public int nId_DocxCobrarParamOpe { get; set; }
        public int? nid_cliente { get; set; }
        public int? nId_Cartera { get; set; }
        public int nId_DocxCobrar { get; set; }
        public av_DocxCobrar av_DocxCobrar { get; set; }
        public int? bEstado { get; set; }
        public string? cDocParam01 { get; set; }
        public string? cDocParam02 { get; set; }
        public string? cDocParam03 { get; set; }
        public string? cDocParam04 { get; set; }
        public string? cDocParam05 { get; set; }
        public string? cDocParam06 { get; set; }
        public string? cDocParam07 { get; set; }
        public string? cDocParam08 { get; set; }
        public string? cDocParam09 { get; set; }
        public string? cDocParam10 { get; set; }
        public string? cDocParam11 { get; set; }
        public string? cDocParam12 { get; set; }
        public string? cDocParam13 { get; set; }
        public string? cDocParam14 { get; set; }
        public string? cDocParam15 { get; set; }
        public string? cDocParam16 { get; set; }
        public string? cDocParam17 { get; set; }
        public string? cDocParam18 { get; set; }
        public string? cDocParam19 { get; set; }
        public string? cDocParam20 { get; set; }
        public string? cDocParam21 { get; set; }
        public string? cDocParam22 { get; set; }
        public string? cDocParam23 { get; set; }
        public string? cDocParam24 { get; set; }
        public string? cDocParam25 { get; set; }
        public string? cDocParam26 { get; set; }
        public string? cDocParam27 { get; set; }
        public string? cDocParam28 { get; set; }
        public string? cDocParam29 { get; set; }
        public string? cDocParam30 { get; set; }
        public string? cDocParam31 { get; set; }
        public string? cDocParam32 { get; set; }
        public string? cDocParam33 { get; set; }
        public string? cDocParam34 { get; set; }
        public string? cDocParam35 { get; set; }
        public string? cDocParam36 { get; set; }
        public string? cDocParam37 { get; set; }
        public string? cDocParam38 { get; set; }
        public string? cDocParam39 { get; set; }
        public string? cDocParam40 { get; set; }
        public string? cDocParam41 { get; set; }
        public string? cDocParam42 { get; set; }
        public string? cDocParam43 { get; set; }
        public string? cDocParam44 { get; set; }
        public string? cDocParam45 { get; set; }
        public string? cDocParam46 { get; set; }
        public string? cDocParam47 { get; set; }
        public string? cDocParam48 { get; set; }
        public string? cDocParam49 { get; set; }
        public string? cDocParam50 { get; set; }
        public DateTime? dDocCobOpe_FecIni { get; set; }
        public DateTime? dFec_Ingreso { get; set; }
        public int? nid_PersDeudor { get; set; }
        public string? cDocParam51 { get; set; }
        public string? cDocParam52 { get; set; }
        public string? cDocParam53 { get; set; }
        public string? cDocParam54 { get; set; }
        public string? cDocParam55 { get; set; }
        public string? cDocParam56 { get; set; }
        public string? cDocParam57 { get; set; }
        public string? cDocParam58 { get; set; }
        public string? cDocParam59 { get; set; }
        public string? cDocParam60 { get; set; }
        public string? cDocParam61 { get; set; }
        public string? cDocParam62 { get; set; }
        public string? cDocParam63 { get; set; }
        public string? cDocParam64 { get; set; }
        public string? cDocParam65 { get; set; }
        public string? cDocParam66 { get; set; }
        public string? cDocParam67 { get; set; }
        public string? cDocParam68 { get; set; }
        public string? cDocParam69 { get; set; }
        public string? cDocParam70 { get; set; }
        public DateTime? dDoc_FecActual { get; set; }
        public int? nId_ContFormRptc { get; set; }
        public string? cDocParam71 { get; set; }
        public string? cDocParam72 { get; set; }
        public string? cDocParam73 { get; set; }
        public string? cDocParam74 { get; set; }
        public string? cDocParam75 { get; set; }
    }
}